apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dmzck4jkh-nodejs 
  janus-idp.io/tekton: dmzck4jkh-nodejs
  backstage.io/kubernetes-id: dmzck4jkh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dmzck4jkh-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  