apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dmzck4jkh-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dmzck4jkh-nodejs 
  name: dmzck4jkh-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dmzck4jkh-nodejs 
